### ISSUE TITLE
Request - Add delay to follow speed

### ISSUE THREAD

**Issue by Areahints** [ricardojoserf/twitter-followers-bot#1]
thanks for this awesome software, i noticed the rate at which the bot follows an account is very fast, how can i introduce a delay?

**Comment by ricardojoserf** [comment]
Hello @Areahints , i just added a variable named "delay_follow" in twitter-bot.py. It is set to 1 second but you can change it to whatever you want, it is in line 10. And I am glad you like the program!!! :)

Best regards,

Ricardo
