### ISSUE TITLE
tweepy error with bot

### ISSUE THREAD

**Issue by Areahints** [ricardojoserf/twitter-followers-bot#2]
```
python twitter-bot.py -g "6.6038839,3.3502615,10km" -l 25 -o follow
```
Traceback (most recent call last):
  File "twitter-bot.py", line 1, in <module>
    import tweepy
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/tweepy/streaming.py", line 355
    def _start(self, async):
                         ^
SyntaxError: invalid syntax

**Comment by ricardojoserf** [comment]
Hi @Areahints . I just downloaded the repository, installed the dependencies and it works both with Python2 and Python3. I am using ElementaryOs, which Linux distro are you using?

Could you please run "sudo pip3 install -r requirements.txt" and regenerate your API keys? 

Please tell me if it is still not working for you, let us try to fix it :)

**Comment by Areahints** [comment]
I am using termux on an android phone, i solved the issue by uninstalling tweepy and reinstalling it

`pip uninstall tweepy `

this removed **tweepy==3.5.0** which is the requirement

then `pip install tweepy`

this installed **tweepy 3.7.0**

I guess python 3.7.2 broke something with the older version of tweepy

now the bot runs fine, though if you dont mind i have another question, any idea how i am supposed to run this in cron? i don't know how to pass the script parameters in the crontab.  i want to run this in cron

`python twitter-bot.py -g "6.6038839,3.3502615,10km" -l 25 -o follow`

**Comment by ricardojoserf** [comment]
Hi @Areahints . Glad you could fix it. The easiest way is to add this line in a bash script and execute that script using Cron. Something like this:

#!/sh
python twitter-bot.py -g "6.6038839,3.3502615,10km" -l 25 -o follow

Hope his helps. 

Cheers,

Ricardo

**Comment by ricardojoserf** [comment]
Well @Areahints  i imagine you managed to use the bash script! I will close the issue, feel free to open a new issue in case you have any error, and to follow me on Github or hit the star button in any of my repositories.

Cheers,

Ricardo
