### ISSUE TITLE
Low Priority: twitter-bot.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by ghost** [ricardojoserf/twitter-followers-bot#4]
When running the code I get 2 errors

twitter-bot.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?

And

twitter-bot.py:65: SyntaxWarning: "is not" with a literal. Did you mean "!="?

Code still runs fine and performs the task needed

**Comment by ricardojoserf** [comment]
Hi @r63b ! I think that error is generated from Python 3.8 and it is just a warning as I am reading here (https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/), but thank you for noticing, I will fix it! :)

**Comment by ricardojoserf** [comment]
Hello again @r63b ! I think it is already fixed, please let me know if you need anything else or I can close the issue :)
